### PR TITLE
UX: added css to remove mobile scrollbar

### PR DESCRIPTION
**Pull request by RyanPaulGannon**
Also ran eslint which has changed the other files, I presume this is correct?

### CODE REVIEW

**Comment by RyanPaulGannon** [comment]
Hasn't worked, it works in the Brave mobile emulator. But testing on mobile now and not working, will revisit.

Also, all checks passed when I ran locally. Will take a look at these too.

**Comment by toniengelhardt** [comment]
I think we can ignore the windows one for now, it seems to have a problem...

**Comment by toniengelhardt** [comment]
This is what I have in another project of mine:

```scss
{
  scrollbar-width: none !important; // Firefox
  -ms-overflow-style: none !important; // IE and Edge
  &::-webkit-scrollbar {
    // Chrome, Safari, Opera
    display: none !important;
    -webkit-appearance: none !important;
  }
}

**Comment by toniengelhardt** [comment]
@RyanPaulGannon I'll merge it to get the lint fixes and then try the solution above.

**Comment by RyanPaulGannon** [comment]
Okay cool, I've just been looking at it currently. Hopefully it works!

**Comment by toniengelhardt** [comment]
> Okay cool, I've just been looking at it currently. Hopefully it works!

Ah ok, then go ahead. You can reopen this when it works. Just needed the lint fixes to avoid conflicts with my PR.

**Comment by RyanPaulGannon** [comment]
Renamed the PR as I'm having no luck with this, will add what I've tried to the issue for reference.

**Pull request merged**
